# Generated by Django 5.2.5 on 2025-08-16 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField(help_text='0.0 to 5.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('fees', models.FloatField(help_text='Fees in K')),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=500)),
                ('stream', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Arts_Commerce', 'Arts & Commerce')], max_length=20)),
                ('exam', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('CUET', 'CUET')], max_length=20)),
            ],
            options={
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['stream'], name='colleges_co_stream_378546_idx'), models.Index(fields=['exam'], name='colleges_co_exam_fac892_idx'), models.Index(fields=['-rating'], name='colleges_co_rating_2495bd_idx')],
            },
        ),
    ]
