# Generated by Django 5.2.5 on 2025-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
